steps:
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'build']
  id: 'build'
  waitFor: ['-']
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'test']
  id: 'test'
  waitFor: ['-']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - Admin
  - --entry-point=Admin
  - --region=europe-west3
  - --trigger-http
  - --runtime=go113
  - --timeout=5s
  - --memory=128MB
  - --max-instances=1
  - --allow-unauthenticated
  - --env-vars-file=.env.yaml
  waitFor: ['build', 'test']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - Expenses
  - --entry-point=Expenses
  - --region=europe-west3
  - --trigger-http
  - --runtime=go113
  - --memory=128MB
  - --max-instances=1
  - --allow-unauthenticated
  waitFor: ['build', 'test']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - Email 
  - --entry-point=Email
  - --region=europe-west3
  - --trigger-topic=cloud-builds
  - --runtime=go113
  - --timeout=5s
  - --memory=128MB
  - --max-instances=1
  waitFor: ['build', 'test']
