steps:
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'build']
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'test']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - AdminSQL
  - --entry-point=HandleAdminSQL
  - --region=europe-west3
  - --trigger-http
  - --runtime=go113
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - Expenses
  - --entry-point=HandleExpenses
  - --region=europe-west3
  - --trigger-http
  - --runtime=go113
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - BuildResultEmailer 
  - --entry-point=BuildResultEmail
  - --region=europe-west3
  - --trigger-topic=cloud-build
  - --runtime=go113
