#!/bin/bash

set -euo pipefail

declare -a arr=(
    "ADMIN_BOT_TOKEN"
    "EXPENSES_BOT_TOKEN"
    "BOT_SQL_ROOT_PASS"
    "BOT_SQL_CONNECTION_NAME"
)

for k in "${arr[@]}"
do
    v=$(printenv ${k}) || { echo "FATAL: ${k} is not set" ; exit 1; }
done

echo "Creating secrets..."

for k in "${arr[@]}"
do
    v=$(printenv ${k})
    gcloud secrets create ${k}
    echo -n "${v}" | gcloud secrets versions add ${k} --data-file=-
done

echo "Success!"
