version: "3"
services:
  mysql:
    image: "mysql:5"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  test:
    image: "mirror.gcr.io/library/golang"
    volumes: ["./:/test"]
    working_dir: "/test"
    command: ["make", "test"]
    environment:
      CI: "true"
networks:
  default:
    external:
      name: cloudbuild
