#!/bin/bash

set -euo pipefail

n=0
until [ "$n" -ge 15 ]
do
    "$@" >/dev/null 2>&1 && echo "" && exit 0 || true
    n=$((n+1))
    echo -n "."
    sleep 1
done

echo -e "\nFailed to execute the following command:"
echo "  \$ $@"
exit 1
