#!/bin/bash

set -euxo pipefail

url=$(gcloud functions describe Expenses --region=europe-west3 --format=json | jq -r .httpsTrigger.url)

curl -X POST ${url} --header "Content-Type: application/json" --data "${1}"
