steps:
- name: 'mirror.gcr.io/library/golang'
  args: ['go', 'test']
  dir: 'admin'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - AdminSQL
  - --source=admin
  - --entry-point=admin.HandleAdminSQL
  - --region=europe-west3
  - --trigger-http
